routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/tasks');
});
Route::get('/tasks', 'TaskController@index');
Route::patch("tasks/{task}/completed", "TaskController@completed")->name('tasks.completed');

Route::resource("tasks", "TaskController");
Auth::routes();

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use Kyslik\ColumnSortable\Sortable;

class Task extends Model
{
    use Sortable;

    protected $fillable = ["title", "description", "status"];
    public $sortable = ['id', 'title', 'created_at', 'created_by', 'completed'];

    /**
     * Creates a relationship between tasks and user.
     *
     * @return void
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Creates a relationship between tasks and user.
     *
     * @return void
     */
    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Creates a relationship between tasks and user.
     *
     * @return void
     */
    public function updatedBy()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Task;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Created a relationship between tasks and user.
     *
     * @return void
     */
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('/tasks');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use App\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return response(Task::all()->jsonSerialize(), Response::HTTP_OK);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'description' => 'required|max:350'
        ]);
        $task = new Task();
        $task->title = $request->title;
        $task->description = $request->description;
        $task->created_by = Auth::id();
        $task->save();

        return response($task->jsonSerialize(), Response::HTTP_CREATED);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findOrFail($id);

        return view('tasks/show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::findOrFail($id);

        return view('tasks/edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'description' => 'required|max:350'
        ]);
        $task->title = $request->title;
        $task->description = $request->description;
        $task->updated_by = Auth::id();
        $task->save();

        return response(null, Response::HTTP_OK);
    }

    /**
     * Sets a task to completed or in progress.
     *
     * @param Task $task
     * @return void
     */
    public function completed(Task $task)
    {
        if ($task->completed == false) {
            $task->completed = true;
            $task->update(["completed" => $task->completed]);
            return redirect('/tasks')->with('success', 'Aufgabe wurde abgeschlossen!');
        } else {
            $task->completed = false;
            $task->update(["completed" => $task->completed]);
            return redirect('/tasks')->with('success', 'Aufgabe wurde als offen markiert!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::findOrFail($id);
        $task->delete();

        return response(null, Response::HTTP_OK);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Aufgabenliste</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/tasks') }}">
                    Aufgabenliste
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                    @if(Auth::user())<li class="nav-item">
                            <a class="nav-link" href="{{ route('tasks.create') }}">Neue Aufgabe hinzufügen</a>
                        </li>
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Anmelden') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Neuer Benutzer') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            @yield('content')
        </div>
        <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>

</html>

resources/views/tasks/create.blade.php
@extends('layouts/app')

@section('title')
<title>Neue Aufgabe hinzufügen</title>
@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>

@if(Auth::user())
<div class="card uper">

    <div class="card-header">
        Neue Aufgabe hinzufügen
    </div>
    <div class="card-body">



        <form method="post" action="{{ route('tasks.store') }}">
            <div class="form-group">
                @csrf
                <label for="title">Aufgabe:</label>
                <input type="text" class="form-control" name="title" value="{{ old('title')}}">
                @if ($errors->has('title'))
                <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="description">Beschreibung:</label>
                <textarea class="form-control" name="description" rows="5" cols="50">{{old('description')}}</textarea>
                @if ($errors->has('description'))
                <span class="text-danger">{{ $errors->first('description') }}</span>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Hinzufügen</button>

            <a class="btn btn-primary" href="{{ route('tasks.index') }}"> Zurück</a>

        </form>
    </div>
</div>
@else
<div class="card-body">
    <h2>Fehler: Benutzer ist nicht angemeldet!</h2>
</div>
@endif
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts/app')

@section('title')
<title>Aufgabe bearbeiten</title>
@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
@if(Auth::user())
<div class="card uper">
    <div class="card-header">
        Aufgabe bearbeiten
    </div>
    <div class="card-body">

        <form method="post" action="{{ route('tasks.update', $task->id) }}">
            <div class="form-group">
                @csrf
                @method('PATCH')
                <label for="title">Aufgabe:</label>
                <input type="text" class="form-control" name="title" value="{{ old('title',$task->title) }}">
                @if ($errors->has('title'))
                <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="description">Beschreibung:</label>
                <textarea class="form-control" name="description" rows="5" cols="50">{{ old('description',$task->description) }}</textarea>
                @if ($errors->has('description'))
                <span class="text-danger">{{ $errors->first('description') }}</span>
                @endif
            </div>
            <button type="submit" class="btn btn-primary">Speichern</button>
            <a class="btn btn-primary" href="{{ route('tasks.index') }}"> Zurück</a>
        </form>
    </div>
</div>
@else
<div class="card-body">
    <h2>Fehler: Benutzer ist nicht angemeldet!</h2>
</div>
@endif
@endsection

resources/views/tasks/index.blade.php
@extends('layouts/app')

@section('title')
<title>Alle Aufgaben</title>
@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="uper">
    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div><br />
    @endif


    <table class="table table-striped">
        <thead>
            <tr>
                <td>@sortablelink('id', 'ID')</td>
                <td>@sortablelink('title', 'Aufgabe')</td>
                <td>@sortablelink('created_at', 'Hinzugefügt am')</td>
                <td>@sortablelink('created_by','Hinzugefügt von')</td>
                <td>@sortablelink('completed','Status')</td>
                <td>Funktionen</td>
                @if(Auth::user())
                <td>Status ändern</td>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($tasks as $task)
            <tr>
                <td>{{$task->id}}</td>
                <td>{{$task->title}}</td>
                <td>{{$task->created_at}}</td>
                <td>{{$task->createdBy->name}}</td>
                <td>{{$task->completed == false ? 'Offen' : 'Abgeschlossen'}}</td>

                <td class="d-flex">
                    @if(Auth::user())
                    <a href="{{ route('tasks.edit', $task->id)}}"><img src="img/tools.png"></img></a>
                    @endif
                    <a href="{{ route('tasks.show', $task->id)}}" class="px-2"><img src="img/view.png"></img></a>
                    @if(Auth::user())
                    <form action="{{ route('tasks.destroy', $task->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <input type="image" src="img/bin.png" name="submit">
                    </form>
                    @endif
                </td>
                @if(Auth::user()) <td>
                    <form action="{{ route('tasks.completed', $task->id)}}" method="post">
                        @csrf
                        @method('PATCH')
                        <button class="btn btn-primary" type="submit">{{$task->completed == true ? 'Als offen markieren' : 'Als abgeschlossen markieren'}}</button>
                    </form>
                </td>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>
    <div>
        @endsection

resources/views/tasks/show.blade.php
@extends('layouts/app')


@section('title')
<title>{{ $task->title }}</title>
@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="uper">
    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div><br />
    @endif
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> {{ $task->title }}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tasks.index') }}"> Zurück</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ID:</strong>
                {{ $task->id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Aufgabe:</strong>
                {{ $task->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Beschreibung:</strong>
                {{ $task->description }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
              {{$task->completed == false ? 'Offen' : 'Abgeschlossen'}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Hinzugefügt am:</strong>
                {{ $task->created_at }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Hinzugefügt von:</strong>
                {{$task->createdBy->name}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Zuletzt bearbeitet am:</strong>
                {{ $task->updated_at }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Zuletzt bearbeitet von:</strong>
                {{optional($task->updatedBy)->name}}
            </div>
        </div>
    </div>
    @endsection